package com.store.dal.entities;
// Generated Aug 30, 2020 2:14:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="comments"
    ,catalog="social_network"
)
public class Comments  implements java.io.Serializable {


     private Integer comId;
     private int postId;
     private String commentAuthor;
     private Date date;
     private String comment;

    public Comments() {
    }

    public Comments(int postId, String commentAuthor, Date date, String comment) {
       this.postId = postId;
       this.commentAuthor = commentAuthor;
       this.date = date;
       this.comment = comment;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="com_id", unique=true, nullable=false)
    public Integer getComId() {
        return this.comId;
    }
    
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    
    @Column(name="post_id", nullable=false)
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }

    
    @Column(name="comment_author", nullable=false)
    public String getCommentAuthor() {
        return this.commentAuthor;
    }
    
    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="comment", nullable=false)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


