package com.store.dal.entities;
// Generated Aug 30, 2020 2:14:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name="posts"
    ,catalog="social_network"
)
public class Posts  implements java.io.Serializable {


     private Integer postId;
     private String postContent;
     private byte[] uploadImage;
     private Date postDate;
     private String userEmail;

    public Posts() {
    }

	
    public Posts(String postContent, Date postDate, String userEmail) {
        this.postContent = postContent;
        this.postDate = postDate;
        this.userEmail = userEmail;
    }
    public Posts(String postContent, byte[] uploadImage, Date postDate, String userEmail) {
       this.postContent = postContent;
       this.uploadImage = uploadImage;
       this.postDate = postDate;
       this.userEmail = userEmail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="post_id", unique=true, nullable=false)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    
    @Column(name="post_content")
    public String getPostContent() {
        return this.postContent;
    }
    
    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    
    @Column(name="upload_image")
    public byte[] getUploadImage() {
        return this.uploadImage;
    }
    
    public void setUploadImage(byte[] uploadImage) {
        this.uploadImage = uploadImage;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="post_date", nullable=false, length=19)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="user_email", nullable=false)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }




}


