package com.store.dal.entities;
// Generated Aug 30, 2020 2:14:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserMessages generated by hbm2java
 */
@Entity
@Table(name="user_messages"
    ,catalog="social_network"
)
public class UserMessages  implements java.io.Serializable {


     private Integer id;
     private int userTo;
     private int userFrom;
     private String msgBody;
     private Date date;
     private String msgSeen;
     private String userEmail;

    public UserMessages() {
    }

    public UserMessages(int userTo, int userFrom, String msgBody, Date date, String msgSeen, String userEmail) {
       this.userTo = userTo;
       this.userFrom = userFrom;
       this.msgBody = msgBody;
       this.date = date;
       this.msgSeen = msgSeen;
       this.userEmail = userEmail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user_to", nullable=false)
    public int getUserTo() {
        return this.userTo;
    }
    
    public void setUserTo(int userTo) {
        this.userTo = userTo;
    }

    
    @Column(name="user_from", nullable=false)
    public int getUserFrom() {
        return this.userFrom;
    }
    
    public void setUserFrom(int userFrom) {
        this.userFrom = userFrom;
    }

    
    @Column(name="msg_body", nullable=false)
    public String getMsgBody() {
        return this.msgBody;
    }
    
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="msg_seen", nullable=false, length=65535)
    public String getMsgSeen() {
        return this.msgSeen;
    }
    
    public void setMsgSeen(String msgSeen) {
        this.msgSeen = msgSeen;
    }

    
    @Column(name="user_email", nullable=false)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }




}


