package com.store.dal.entities;
// Generated Aug 30, 2020 2:14:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="social_network"
)
public class Users  implements java.io.Serializable {


     private String userEmail;
     private String FName;
     private String LName;
     private String userName;
     private String describeUser;
     private String relationship;
     private String userPassword;
     private String userCountry;
     private String userGendre;
     private String userBirthday;
     private byte[] userImage;
     private byte[] userCover;
     private Date userRegDate;
     private String status;
     private String posts;
     private String recoveryAccount;

    public Users() {
    }

	
    public Users(String userEmail, String FName, String LName, String userName, String userPassword, String userCountry, String userGendre, String userBirthday, Date userRegDate) {
        this.userEmail = userEmail;
        this.FName = FName;
        this.LName = LName;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userCountry = userCountry;
        this.userGendre = userGendre;
        this.userBirthday = userBirthday;
        this.userRegDate = userRegDate;
    }
    public Users(String userEmail, String FName, String LName, String userName, String describeUser, String relationship, String userPassword, String userCountry, String userGendre, String userBirthday, byte[] userImage, byte[] userCover, Date userRegDate, String status, String posts, String recoveryAccount) {
       this.userEmail = userEmail;
       this.FName = FName;
       this.LName = LName;
       this.userName = userName;
       this.describeUser = describeUser;
       this.relationship = relationship;
       this.userPassword = userPassword;
       this.userCountry = userCountry;
       this.userGendre = userGendre;
       this.userBirthday = userBirthday;
       this.userImage = userImage;
       this.userCover = userCover;
       this.userRegDate = userRegDate;
       this.status = status;
       this.posts = posts;
       this.recoveryAccount = recoveryAccount;
    }
   
     @Id 

    
    @Column(name="user_email", unique=true, nullable=false)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="f_name", nullable=false, length=65535)
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }

    
    @Column(name="l_name", nullable=false, length=65535)
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }

    
    @Column(name="user_name", nullable=false, length=65535)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="describe_user")
    public String getDescribeUser() {
        return this.describeUser;
    }
    
    public void setDescribeUser(String describeUser) {
        this.describeUser = describeUser;
    }

    
    @Column(name="Relationship", length=65535)
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    
    @Column(name="user_password", nullable=false)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="user_country", nullable=false, length=65535)
    public String getUserCountry() {
        return this.userCountry;
    }
    
    public void setUserCountry(String userCountry) {
        this.userCountry = userCountry;
    }

    
    @Column(name="user_gendre", nullable=false, length=65535)
    public String getUserGendre() {
        return this.userGendre;
    }
    
    public void setUserGendre(String userGendre) {
        this.userGendre = userGendre;
    }

    
    @Column(name="user_birthday", nullable=false, length=65535)
    public String getUserBirthday() {
        return this.userBirthday;
    }
    
    public void setUserBirthday(String userBirthday) {
        this.userBirthday = userBirthday;
    }

    
    @Column(name="user_image")
    public byte[] getUserImage() {
        return this.userImage;
    }
    
    public void setUserImage(byte[] userImage) {
        this.userImage = userImage;
    }

    
    @Column(name="user_cover")
    public byte[] getUserCover() {
        return this.userCover;
    }
    
    public void setUserCover(byte[] userCover) {
        this.userCover = userCover;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="user_reg_date", nullable=false, length=19)
    public Date getUserRegDate() {
        return this.userRegDate;
    }
    
    public void setUserRegDate(Date userRegDate) {
        this.userRegDate = userRegDate;
    }

    
    @Column(name="status", length=65535)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="posts", length=65535)
    public String getPosts() {
        return this.posts;
    }
    
    public void setPosts(String posts) {
        this.posts = posts;
    }

    
    @Column(name="recovery_account")
    public String getRecoveryAccount() {
        return this.recoveryAccount;
    }
    
    public void setRecoveryAccount(String recoveryAccount) {
        this.recoveryAccount = recoveryAccount;
    }




}


